<a href="https://colab.research.google.com/github/Yaroslav1121/MachineLearning/blob/main/%D0%9B%D0%B0%D0%B1_4_%D0%97%D0%B0%D0%B2%D0%B4_2_%D0%9A%D0%BB%D0%B8%D0%BC%D1%96%D0%BA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
from google.colab import drive
import pandas as pd

# Підключення Google Drive
drive.mount('/content/drive')

# Читання CSV-файлу з правильним роздільником (кома)
df=pd.read_csv('/content/drive/My Drive/Colab Notebooks/tested.csv', sep=',')

# 1. Виведення перших 5 рядків для перевірки
print(df.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
   PassengerId  Survived  Pclass  \
0          892         0       3
1          893         1       3
2          894         0       2
3          895         0       3
4          896         1       3

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                     Myles, Mr. Thomas Francis    male  62.0      0      0
3                              Wirz, Mr. Albert    male  27.0      0      0
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1

    Ticket     Fare Cabin Embarked
0   330911   7.8292   NaN        Q
1   363272   7.0000   NaN        S
2   240276   9.6875   NaN        Q
3   315154   8.6625   NaN        S
4  3101298  12.2875   NaN        S

In [3]:
# 2. Визначити розмір датасета.
df.shape

(418, 12)

In [4]:
# 3. Визначити тип даних.
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [5]:
# 4. Визначити наявність пропущених значень. При наявності, замінити
# пропущені значення на середнє значення.

# Перевіряємо кількість пропущених значень.
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [11]:
# Заміняємо пропущені значення на середні.
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Fare'].fillna(df['Fare'].median(), inplace=True)

In [12]:
# Ще раз перевіряємо наявність пропущених значень
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64

In [13]:
# 6. Перевірити наявність дублікатів. При наявності видалити дублікати.
df.duplicated().sum()

0

In [14]:
# 7. Вивести описову статистику датасету describe()
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000,418.000000
mean,1100.500000,0.363636,2.265550,29.599282,0.447368,0.392344,35.576535
std,120.810458,0.481622,0.841838,12.703770,0.896760,0.981429,55.850103
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,23.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,35.750000,1.000000,0.000000,31.471875
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [15]:
# 8. Видалити стовпчик Cabin
df.drop('Cabin', axis=1, inplace=True)
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S

In [25]:
# 9. Сформувати датасет з обраними стовпцями:['Survived', 'Pclass', 'Sex', 'Age', 'Fare']]
selected_columns = ['Survived', 'Pclass', 'Sex', 'Age', 'Fare']
titanic_dts = df[selected_columns]
titanic_dts.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  34.5   7.8292
1         1       3  female  47.0   7.0000
2         0       2    male  62.0   9.6875
3         0       3    male  27.0   8.6625
4         1       3  female  22.0  12.2875

In [26]:
# 10.Замінити бінарні ознаки (Стать) на 0 і 1

# Перевірка унікальних значень у стовпці 'Sex'
titanic_dts['Sex'].unique()

# Замінюємо значення: 'male' на 1, 'female' на 0
titanic_dts.loc[:, 'Sex'] = titanic_dts['Sex'].map({'male': 1, 'female': 0})

# Перевірка після заміни
titanic_dts['Sex'].unique()

# Виведення перших 5 рядків для перевірки
titanic_dts.head()

   Survived  Pclass Sex   Age     Fare
0         0       3   1  34.5   7.8292
1         1       3   0  47.0   7.0000
2         0       2   1  62.0   9.6875
3         0       3   1  27.0   8.6625
4         1       3   0  22.0  12.2875

In [18]:
# 11.Ще раз перевірити кількість пропущених даних (впевнитись, що їх немає).
titanic_dts.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
Fare        0
dtype: int64

In [19]:
# 12.Вивести 5 перших рядків датасету.
titanic_dts.head(5)

   Survived  Pclass Sex   Age     Fare
0         0       3   1  34.5   7.8292
1         1       3   0  47.0   7.0000
2         0       2   1  62.0   9.6875
3         0       3   1  27.0   8.6625
4         1       3   0  22.0  12.2875

In [ ]:
# 13. Вивести 5 останніх рядків датасету.
titanic_dts.tail(5)

     Survived  Pclass Sex   Age      Fare
413         0       3   1  27.0    8.0500
414         1       1   0  39.0  108.9000
415         0       3   1  38.5    7.2500
416         0       3   1  27.0    8.0500
417         0       3   1  27.0   22.3583

In [ ]:
# 14.Аналіз виживання залежно від статі: Обчисліть відсоток виживання
# для кожної статі. Чи була різниця у виживанні між чоловіками та жінками?
# Групування за стовпцем 'Sex' і обчислення середнього для 'Survived'
survival_rate = titanic_dts.groupby('Sex')['Survived'].mean() * 100
print(survival_rate)

Sex
0    100.0
1      0.0
Name: Survived, dtype: float64

In [27]:
from sklearn.model_selection import train_test_split

# Вибір ознак та цільової змінної
X = titanic_dts[['Pclass', 'Sex', 'Age', 'Fare']]
y = titanic_dts['Survived']

# Розділення на тренувальну та тестову вибірки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Класифікатор Logistic Regression
logistic_model = LogisticRegression()
logistic_model.fit(X_train, y_train)
y_pred_logistic = logistic_model.predict(X_test)

# Оцінка точності
accuracy_logistic = accuracy_score(y_test, y_pred_logistic)
print(f"Accuracy of Logistic Regression: {accuracy_logistic:.2f}")

Accuracy of Logistic Regression: 1.00

In [29]:
from sklearn.ensemble import RandomForestClassifier

# Класифікатор Random Forest
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

# Оцінка точності
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Accuracy of Random Forest: {accuracy_rf:.2f}")

Accuracy of Random Forest: 1.00

In [30]:
from sklearn.svm import SVC

# Класифікатор Support Vector Classifier
svc_model = SVC()
svc_model.fit(X_train, y_train)
y_pred_svc = svc_model.predict(X_test)

# Оцінка точності
accuracy_svc = accuracy_score(y_test, y_pred_svc)
print(f"Accuracy of Support Vector Classifier: {accuracy_svc:.2f}")

Accuracy of Support Vector Classifier: 0.61

Оптимізація параметрів для всіх класифікаторів

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# Налаштування параметрів для Logistic Regression
param_grid_logistic = {
    'C': [0.01, 0.1, 1, 10, 100],
    'solver': ['lbfgs', 'liblinear']
}

logistic_model = LogisticRegression(max_iter=500)
grid_logistic = GridSearchCV(logistic_model, param_grid_logistic, cv=5)
grid_logistic.fit(X_train, y_train)

print(f"Best parameters for Logistic Regression: {grid_logistic.best_params_}")

Best parameters for Logistic Regression: {'C': 0.1, 'solver': 'lbfgs'}

In [32]:
from sklearn.ensemble import RandomForestClassifier

# Налаштування параметрів для Random Forest
param_grid_rf = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10]
}

rf_model = RandomForestClassifier()
grid_rf = GridSearchCV(rf_model, param_grid_rf, cv=5)
grid_rf.fit(X_train, y_train)

print(f"Best parameters for Random Forest: {grid_rf.best_params_}")

Best parameters for Random Forest: {'max_depth': None, 'min_samples_split': 2, 'n_estimators': 50}

In [33]:
from sklearn.svm import SVC

# Налаштування параметрів для SVC
param_grid_svc = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto']
}

svc_model = SVC()
grid_svc = GridSearchCV(svc_model, param_grid_svc, cv=5)
grid_svc.fit(X_train, y_train)

print(f"Best parameters for SVC: {grid_svc.best_params_}")

Best parameters for SVC: {'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}

 Оцінка моделей та метрики

In [34]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Логістична регресія
logistic_best = grid_logistic.best_estimator_
y_pred_logistic = logistic_best.predict(X_test)

# Метрики
print(f"Logistic Regression Accuracy: {accuracy_score(y_test, y_pred_logistic)}")
print(confusion_matrix(y_test, y_pred_logistic))
print(classification_report(y_test, y_pred_logistic))

Logistic Regression Accuracy: 1.0
[[50  0]
 [ 0 34]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      1.00      1.00        34

    accuracy                           1.00        84
   macro avg       1.00      1.00      1.00        84
weighted avg       1.00      1.00      1.00        84

In [35]:
# Random Forest
rf_best = grid_rf.best_estimator_
y_pred_rf = rf_best.predict(X_test)

# Метрики
print(f"Random Forest Accuracy: {accuracy_score(y_test, y_pred_rf)}")
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

Random Forest Accuracy: 1.0
[[50  0]
 [ 0 34]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      1.00      1.00        34

    accuracy                           1.00        84
   macro avg       1.00      1.00      1.00        84
weighted avg       1.00      1.00      1.00        84

In [36]:
# SVC
svc_best = grid_svc.best_estimator_
y_pred_svc = svc_best.predict(X_test)

# Метрики
print(f"SVC Accuracy: {accuracy_score(y_test, y_pred_svc)}")
print(confusion_matrix(y_test, y_pred_svc))
print(classification_report(y_test, y_pred_svc))

SVC Accuracy: 1.0
[[50  0]
 [ 0 34]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      1.00      1.00        34

    accuracy                           1.00        84
   macro avg       1.00      1.00      1.00        84
weighted avg       1.00      1.00      1.00        84

In [37]:
import numpy as np

# Випадковий вибір 10 прикладів із тестової вибірки
indices = np.random.choice(X_test.index, size=10, replace=False)
X_sample = X_test.loc[indices]
y_sample = y_test.loc[indices]

# Прогнозування для найкращої моделі (наприклад, Random Forest)
y_pred_sample = rf_best.predict(X_sample)

# Виведення результатів
print(f"Actual values: {y_sample.values}")
print(f"Predicted values: {y_pred_sample}")

Actual values: [1 0 0 0 1 1 1 0 1 0]
Predicted values: [1 0 0 0 1 1 1 0 1 0]